# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 18:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twote', '0009_outgoingconfig_outgoingtweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetweetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='outgoingconfig',
            name='ignore_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
